name = "gdx-travel"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "gdx-travel-db"
database_id = "6e855a95-e6d5-47f3-8bc4-e4dd18e76347"
